version: '3.8'

services:
  poker-bot:
    build: .
    ports:
      - "8443:8443"
    environment:
      - RUN_MODE=webhook
      - WEBHOOK_HOST=https://yourdomain.com
      - WEBHOOK_SECRET=your_secret_token
    volumes:
      - ./ssl:/app/ssl:ro
    restart: unless-stopped

  # Nginx для прокси и SSL termination
  nginx:
    image: nginx:alpine
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - poker-bot
    restart: unless-stopped