services:
  - type: worker
    name: poker-mentor-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python run.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: 8323676065:AAHBKbwyjpTPQjE7v9aRIElmSOk1A7uHtjY
      - key: DATABASE_URL
        value: sqlite:///poker_mentor.db